---
description: Pipeline for processing Managed System logs
processors:
  - rename:
      field: message
      target_field: beyondinsight_password_safe.managedsystem

  - fingerprint:
      fields:
        - beyondinsight_password_safe.managedsystem.ManagedSystemID
      target_field: "_id"

####################
# Scripts for processing input #
####################
  - script:
      description: Drops null/empty values recursively.
      lang: painless
      source: |
        boolean dropEmptyFields(Object object) {
          if (object == null || object == "") {
            return true;
          } else if (object instanceof Map) {
            ((Map) object).values().removeIf(value -> dropEmptyFields(value));
            return (((Map) object).size() == 0);
          } else if (object instanceof List) {
            ((List) object).removeIf(value -> dropEmptyFields(value));
            return (((List) object).length == 0);
          }
          return false;
        }
        dropEmptyFields(ctx);

  - script:
      description: Convert Additional Info keys to snake case.
      tag: additional-info-keys-to-snake-case
      lang: painless
      source: |
        Map keysToSnakeCase(Map m) {
          def regex = /_?([a-z])([A-Z]+)/;
          def snakeCaseMap = [:];

          for (entry in m.entrySet()) {
            def k = entry.getKey();
            def v = entry.getValue();

            if (v instanceof Map) {
              v = keysToSnakeCase(v);
            } else if (v instanceof List) {
              for (int i = 0; i < v.size(); i++) {
                def item = v.get(i);
                if (item instanceof Map) {
                  v.set(i, keysToSnakeCase(item));
                }
              }
            }

            k = regex.matcher(k).replaceAll('$1_$2').toLowerCase();
            snakeCaseMap.put(k, v);
          }
          return snakeCaseMap;
        }

        if (ctx.beyondinsight_password_safe.managedsystem != null) {
          ctx.beyondinsight_password_safe.managedsystem = keysToSnakeCase(ctx.beyondinsight_password_safe.managedsystem);
        }


####################
# ECS Fields #
####################
  - set:
      field: ecs.version
      value: '8.11.0'

  - set:
      field: event.kind
      value: asset

  - append:
      field: event.category
      value: iam

  - append:
      field: event.type
      value: info

  - set:
      field: event.dataset
      value: beyondinsight_password_safe.managedsystem

  - set:
      field: event.module
      value: beyondinsight_password_safe

on_failure:
  - append:
      field: error.message
      value: '{{{_ingest.on_failure_message}}}'
  - set:
      field: event.kind
      value: pipeline_error