---
description: Pipeline for processing sample logs
processors:
  - set:
      field: event.ingested
      value: "{{{_ingest.timestamp}}}"
      ignore_empty_value: true
      ignore_failure: true
on_failure:
  - append:
      field: error.message
      value: '{{{_ingest.on_failure_message}}}'
  - set:
      field: event.kind
      value: pipeline_error