rules:
  #### UserAudits ####
  - path: "/BeyondTrust/api/public/v3/Auth/SignAppin"
    methods: ["POST"]
    request_headers:
      Authorization: ['PS-Auth key=abcd1234byiapitoken;runas=testuser;pwd=\[password\];']
      Content-Type: ['application/json']
    responses:
      - status_code: 200
        headers:
          Content-Type: ['application/json']
          Set-Cookie: ['ASP.NET_SessionId=iijfdzn51fdh01axylh1nnd1']
        body: |
          {
            "UserId": 1,
            "SID": null,
            "EmailAddress": "test.user@example.com",
            "UserName": "testuser",
            "Name": "Test User"
          }
  - path: "/BeyondTrust/api/public/v3/UserAudits"
    methods: ["GET"]
    request_headers:
      Content-Type: ['application/json']
      Cookie: ['ASP.NET_SessionId=iijfdzn51fdh01axylh1nnd1']
    responses:
      - status_code: 200
        headers:
          Content-Type: ['application/json']
        body: |
          {
            "TotalCount": 1,
            "Data": [
              {
                "AuditID": 1,
                "ActionType": "Login",
                "Section": "PMM API SignAppIn",
                "UserID": 6,
                "UserName": "test.user@example.com",
                "IPAddress": "216.160.83.56",
                "CreateDate": "2024-12-12T10:24:26.323Z"
              }
            ]
          }
  - path: "/BeyondTrust/api/public/v3/Sessions"
    methods: ["GET"]
    request_headers:
      Content-Type: ['application/json']
      Cookie: ['ASP.NET_SessionId=iijfdzn51fdh01axylh1nnd1']
    responses:
      - status_code: 200
        headers:
          Content-Type: ['application/json']
        body: |
          [
            {
              "SessionID": 1,
              "UserID": 6,
              "NodeID": "a5c29153-b351-41f1-a12b-0c4da9408d79",
              "Status": 0,
              "ArchiveStatus": 0,
              "Protocol": 0,
              "StartTime": null,
              "EndTime": null,
              "Duration": 0,
              "AssetName": "localhost",
              "ManagedSystemID": 13,
              "ManagedAccountID": null,
              "ManagedAccountName": "example.com\\sdfsfdf",
              "RecordKey": "3958d725d16119a95e64af424a7f8dfsf13f1be4a6cd34earwr324454bcecce70ee37cbaed",
              "Token": "bcb8c654b827a4465846c96b5d6dd8dsfsdf2935c6a1f02f067fd0976dfsdf6d7370c22"
            }
          ]
  - path: "/BeyondTrust/api/public/v3/ManagedAccounts"
    methods: ["GET"]
    request_headers:
      Content-Type: ['application/json']
      Cookie: ['ASP.NET_SessionId=iijfdzn51fdh01axylh1nnd1']
    responses:
      - status_code: 200
        headers:
          Content-Type: ['application/json']
        body: "[\n  {\n    \"PlatformID\": 4,\n    \"SystemId\": 5,\n    \"SystemName\": \"KittenGrowth\",\n    \"InstanceName\": \"\",\n    \"DomainName\": null,\n    \"AccountId\": 5,\n    \"AccountName\": \"fsd.Iredfsne\",\n    \"UserPrincipalName\": null,\n    \"ApplicationID\": null,\n    \"ApplicationDisplayName\": null,\n    \"MaximumReleaseDuration\": 525600,\n    \"DefaultReleaseDuration\": 120,\n    \"LastChangeDate\": \"2024-12-10T08:57:45.9\",\n    \"NextChangeDate\": null,\n    \"ChangeState\": 0,\n    \"IsChanging\": false,\n    \"IsISAAccess\": true,\n    \"PreferredNodeID\": \"e0148f55-f3c6-4049-673e-5093b6bcf831\"\n  }\n] \n"
  - path: "/BeyondTrust/api/public/v3/ManagedSystems"
    methods: ["GET"]
    request_headers:
      Content-Type: ['application/json']
      Cookie: ['ASP.NET_SessionId=iijfdzn51fdh01axylh1nnd1']
    responses:
      - status_code: 200
        headers:
          Content-Type: ['application/json']
        body: "{\n \"TotalCount\": 1,\n \"Data\": [\n    {\n        \"ManagedSystemID\": 13,\n        \"EntityTypeID\": 1,\n        \"AssetID\": 13,\n        \"DatabaseID\": null,\n        \"DirectoryID\": null,\n        \"CloudID\": null,\n        \"WorkgroupID\": 1,\n        \"HostName\": \"AardvarkAgreement\",\n        \"DnsName\": \"AardvarkAgreement.example.com\",\n        \"IPAddress\": \"172.16.152.110\",\n        \"InstanceName\": null,\n        \"IsDefaultInstance\": null,\n        \"Template\": null,\n        \"ForestName\": null,\n        \"UseSSL\": null,\n        \"OracleInternetDirectoryID\": null,\n        \"OracleInternetDirectoryServiceName\": null,\n        \"SystemName\": \"AardvarkAgreement\",\n        \"PlatformID\": 4,\n        \"NetBiosName\": null,\n        \"Port\": null,\n        \"Timeout\": 30,\n        \"Description\": null,\n        \"ContactEmail\": null,\n        \"PasswordRuleID\": 0,\n        \"DSSKeyRuleID\": 0,\n        \"ReleaseDuration\": 120,\n        \"MaxReleaseDuration\": 525600,\n        \"ISAReleaseDuration\": 120,\n        \"AutoManagementFlag\": true,\n        \"FunctionalAccountID\": 14,\n        \"LoginAccountID\": null,\n        \"ElevationCommand\": null,\n        \"SshKeyEnforcementMode\": 0,\n        \"CheckPasswordFlag\": false,\n        \"ChangePasswordAfterAnyReleaseFlag\": false,\n        \"ResetPasswordOnMismatchFlag\": false,\n        \"ChangeFrequencyType\": \"first\",\n        \"ChangeFrequencyDays\": 30,\n        \"ChangeTime\": \"23:30\",\n        \"AccountNameFormat\": 0,\n        \"RemoteClientType\": \"None\",\n        \"ApplicationHostID\": null,\n        \"IsApplicationHost\": false,\n        \"AccessURL\": null\n     }\n  ]       \n}             "
